server:
  port: 9086
fcubs:
  de-service-url: http://10.1.12.71:8101/FCUBSDEService/FCUBSDEService
  source: FCAT
  user-id: TAKEON01
  password: Oracle@2
  branch: 101
  service: FCUBSDEService
  operation: CreateMjrnlbook
