
package com.bayeesoft.stub;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "FCUBSDEServiceSEI", targetNamespace = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FCUBSDEServiceSEI {


    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.AUTHORIZEDEBATCHBROWSERFSFSRES
     */
    @WebMethod(operationName = "AuthorizeDEBatchBrowserFS")
    @WebResult(name = "AUTHORIZEDEBATCHBROWSER_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/AuthorizeDEBatchBrowserFSRequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/AuthorizeDEBatchBrowserFSResponse")
    public AUTHORIZEDEBATCHBROWSERFSFSRES authorizeDEBatchBrowserFS(
        @WebParam(name = "AUTHORIZEDEBATCHBROWSER_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        AUTHORIZEDEBATCHBROWSERFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.AUTHORIZEDEBATCHBROWSERIOPKRES
     */
    @WebMethod(operationName = "AuthorizeDEBatchBrowserIO")
    @WebResult(name = "AUTHORIZEDEBATCHBROWSER_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/AuthorizeDEBatchBrowserIORequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/AuthorizeDEBatchBrowserIOResponse")
    public AUTHORIZEDEBATCHBROWSERIOPKRES authorizeDEBatchBrowserIO(
        @WebParam(name = "AUTHORIZEDEBATCHBROWSER_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        AUTHORIZEDEBATCHBROWSERIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.AUTHORIZEDEBRANCHRESTFSFSRES
     */
    @WebMethod(operationName = "AuthorizeDEBranchRestFS")
    @WebResult(name = "AUTHORIZEDEBRANCHREST_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/AuthorizeDEBranchRestFSRequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/AuthorizeDEBranchRestFSResponse")
    public AUTHORIZEDEBRANCHRESTFSFSRES authorizeDEBranchRestFS(
        @WebParam(name = "AUTHORIZEDEBRANCHREST_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        AUTHORIZEDEBRANCHRESTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.AUTHORIZEDEBRANCHRESTIOPKRES
     */
    @WebMethod(operationName = "AuthorizeDEBranchRestIO")
    @WebResult(name = "AUTHORIZEDEBRANCHREST_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/AuthorizeDEBranchRestIORequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/AuthorizeDEBranchRestIOResponse")
    public AUTHORIZEDEBRANCHRESTIOPKRES authorizeDEBranchRestIO(
        @WebParam(name = "AUTHORIZEDEBRANCHREST_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        AUTHORIZEDEBRANCHRESTIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.AUTHORIZEDEDRAFTISSUERMAINTFSFSRES
     */
    @WebMethod(operationName = "AuthorizeDEDraftIssuerMaintFS")
    @WebResult(name = "AUTHORIZEDEDRAFTISSUERMAINT_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/AuthorizeDEDraftIssuerMaintFSRequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/AuthorizeDEDraftIssuerMaintFSResponse")
    public AUTHORIZEDEDRAFTISSUERMAINTFSFSRES authorizeDEDraftIssuerMaintFS(
        @WebParam(name = "AUTHORIZEDEDRAFTISSUERMAINT_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        AUTHORIZEDEDRAFTISSUERMAINTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.AUTHORIZEDEDRAFTISSUERMAINTIOPKRES
     */
    @WebMethod(operationName = "AuthorizeDEDraftIssuerMaintIO")
    @WebResult(name = "AUTHORIZEDEDRAFTISSUERMAINT_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/AuthorizeDEDraftIssuerMaintIORequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/AuthorizeDEDraftIssuerMaintIOResponse")
    public AUTHORIZEDEDRAFTISSUERMAINTIOPKRES authorizeDEDraftIssuerMaintIO(
        @WebParam(name = "AUTHORIZEDEDRAFTISSUERMAINT_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        AUTHORIZEDEDRAFTISSUERMAINTIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.AUTHORIZEDEMULTIOFFSETFSFSRES
     */
    @WebMethod(operationName = "AuthorizeDEMultiOffsetFS")
    @WebResult(name = "AUTHORIZEDEMULTIOFFSET_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/AuthorizeDEMultiOffsetFSRequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/AuthorizeDEMultiOffsetFSResponse")
    public AUTHORIZEDEMULTIOFFSETFSFSRES authorizeDEMultiOffsetFS(
        @WebParam(name = "AUTHORIZEDEMULTIOFFSET_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        AUTHORIZEDEMULTIOFFSETFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.AUTHORIZEDEMULTIOFFSETIOPKRES
     */
    @WebMethod(operationName = "AuthorizeDEMultiOffsetIO")
    @WebResult(name = "AUTHORIZEDEMULTIOFFSET_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/AuthorizeDEMultiOffsetIORequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/AuthorizeDEMultiOffsetIOResponse")
    public AUTHORIZEDEMULTIOFFSETIOPKRES authorizeDEMultiOffsetIO(
        @WebParam(name = "AUTHORIZEDEMULTIOFFSET_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        AUTHORIZEDEMULTIOFFSETIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.AUTHORIZEMJRNLTEMPLATEFSFSRES
     */
    @WebMethod(operationName = "AuthorizeMjrnlTemplateFS")
    @WebResult(name = "AUTHORIZEMJRNLTEMPLATE_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/AuthorizeMjrnlTemplateFSRequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/AuthorizeMjrnlTemplateFSResponse")
    public AUTHORIZEMJRNLTEMPLATEFSFSRES authorizeMjrnlTemplateFS(
        @WebParam(name = "AUTHORIZEMJRNLTEMPLATE_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        AUTHORIZEMJRNLTEMPLATEFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.AUTHORIZEMJRNLTEMPLATEIOPKRES
     */
    @WebMethod(operationName = "AuthorizeMjrnlTemplateIO")
    @WebResult(name = "AUTHORIZEMJRNLTEMPLATE_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/AuthorizeMjrnlTemplateIORequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/AuthorizeMjrnlTemplateIOResponse")
    public AUTHORIZEMJRNLTEMPLATEIOPKRES authorizeMjrnlTemplateIO(
        @WebParam(name = "AUTHORIZEMJRNLTEMPLATE_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        AUTHORIZEMJRNLTEMPLATEIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.AUTHORIZEMJRNLBOOKFSFSRES
     */
    @WebMethod(operationName = "AuthorizeMjrnlbookFS")
    @WebResult(name = "AUTHORIZEMJRNLBOOK_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/AuthorizeMjrnlbookFSRequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/AuthorizeMjrnlbookFSResponse")
    public AUTHORIZEMJRNLBOOKFSFSRES authorizeMjrnlbookFS(
        @WebParam(name = "AUTHORIZEMJRNLBOOK_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        AUTHORIZEMJRNLBOOKFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.AUTHORIZEMJRNLBOOKIOPKRES
     */
    @WebMethod(operationName = "AuthorizeMjrnlbookIO")
    @WebResult(name = "AUTHORIZEMJRNLBOOK_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/AuthorizeMjrnlbookIORequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/AuthorizeMjrnlbookIOResponse")
    public AUTHORIZEMJRNLBOOKIOPKRES authorizeMjrnlbookIO(
        @WebParam(name = "AUTHORIZEMJRNLBOOK_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        AUTHORIZEMJRNLBOOKIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.AUTHORIZESINGLEJRNLFSFSRES
     */
    @WebMethod(operationName = "AuthorizeSingleJrnlFS")
    @WebResult(name = "AUTHORIZESINGLEJRNL_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/AuthorizeSingleJrnlFSRequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/AuthorizeSingleJrnlFSResponse")
    public AUTHORIZESINGLEJRNLFSFSRES authorizeSingleJrnlFS(
        @WebParam(name = "AUTHORIZESINGLEJRNL_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        AUTHORIZESINGLEJRNLFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.AUTHORIZESINGLEJRNLIOPKRES
     */
    @WebMethod(operationName = "AuthorizeSingleJrnlIO")
    @WebResult(name = "AUTHORIZESINGLEJRNL_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/AuthorizeSingleJrnlIORequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/AuthorizeSingleJrnlIOResponse")
    public AUTHORIZESINGLEJRNLIOPKRES authorizeSingleJrnlIO(
        @WebParam(name = "AUTHORIZESINGLEJRNL_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        AUTHORIZESINGLEJRNLIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.AUTHORIZETELLERFSFSRES
     */
    @WebMethod(operationName = "AuthorizeTellerFS")
    @WebResult(name = "AUTHORIZETELLER_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/AuthorizeTellerFSRequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/AuthorizeTellerFSResponse")
    public AUTHORIZETELLERFSFSRES authorizeTellerFS(
        @WebParam(name = "AUTHORIZETELLER_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        AUTHORIZETELLERFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.AUTHORIZETELLERIOPKRES
     */
    @WebMethod(operationName = "AuthorizeTellerIO")
    @WebResult(name = "AUTHORIZETELLER_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/AuthorizeTellerIORequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/AuthorizeTellerIOResponse")
    public AUTHORIZETELLERIOPKRES authorizeTellerIO(
        @WebParam(name = "AUTHORIZETELLER_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        AUTHORIZETELLERIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.CLOSEDEBRANCHRESTFSFSRES
     */
    @WebMethod(operationName = "CloseDEBranchRestFS")
    @WebResult(name = "CLOSEDEBRANCHREST_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/CloseDEBranchRestFSRequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/CloseDEBranchRestFSResponse")
    public CLOSEDEBRANCHRESTFSFSRES closeDEBranchRestFS(
        @WebParam(name = "CLOSEDEBRANCHREST_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        CLOSEDEBRANCHRESTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.CLOSEDEBRANCHRESTIOPKRES
     */
    @WebMethod(operationName = "CloseDEBranchRestIO")
    @WebResult(name = "CLOSEDEBRANCHREST_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/CloseDEBranchRestIORequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/CloseDEBranchRestIOResponse")
    public CLOSEDEBRANCHRESTIOPKRES closeDEBranchRestIO(
        @WebParam(name = "CLOSEDEBRANCHREST_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        CLOSEDEBRANCHRESTIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.CLOSEDEDRAFTISSUERMAINTFSFSRES
     */
    @WebMethod(operationName = "CloseDEDraftIssuerMaintFS")
    @WebResult(name = "CLOSEDEDRAFTISSUERMAINT_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/CloseDEDraftIssuerMaintFSRequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/CloseDEDraftIssuerMaintFSResponse")
    public CLOSEDEDRAFTISSUERMAINTFSFSRES closeDEDraftIssuerMaintFS(
        @WebParam(name = "CLOSEDEDRAFTISSUERMAINT_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        CLOSEDEDRAFTISSUERMAINTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.CLOSEDEDRAFTISSUERMAINTIOPKRES
     */
    @WebMethod(operationName = "CloseDEDraftIssuerMaintIO")
    @WebResult(name = "CLOSEDEDRAFTISSUERMAINT_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/CloseDEDraftIssuerMaintIORequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/CloseDEDraftIssuerMaintIOResponse")
    public CLOSEDEDRAFTISSUERMAINTIOPKRES closeDEDraftIssuerMaintIO(
        @WebParam(name = "CLOSEDEDRAFTISSUERMAINT_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        CLOSEDEDRAFTISSUERMAINTIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.CLOSEMJRNLTEMPLATEFSFSRES
     */
    @WebMethod(operationName = "CloseMjrnlTemplateFS")
    @WebResult(name = "CLOSEMJRNLTEMPLATE_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/CloseMjrnlTemplateFSRequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/CloseMjrnlTemplateFSResponse")
    public CLOSEMJRNLTEMPLATEFSFSRES closeMjrnlTemplateFS(
        @WebParam(name = "CLOSEMJRNLTEMPLATE_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        CLOSEMJRNLTEMPLATEFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.CLOSEMJRNLTEMPLATEIOPKRES
     */
    @WebMethod(operationName = "CloseMjrnlTemplateIO")
    @WebResult(name = "CLOSEMJRNLTEMPLATE_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/CloseMjrnlTemplateIORequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/CloseMjrnlTemplateIOResponse")
    public CLOSEMJRNLTEMPLATEIOPKRES closeMjrnlTemplateIO(
        @WebParam(name = "CLOSEMJRNLTEMPLATE_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        CLOSEMJRNLTEMPLATEIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.CREATEDEBRANCHRESTFSFSRES
     */
    @WebMethod(operationName = "CreateDEBranchRestFS")
    @WebResult(name = "CREATEDEBRANCHREST_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/CreateDEBranchRestFSRequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/CreateDEBranchRestFSResponse")
    public CREATEDEBRANCHRESTFSFSRES createDEBranchRestFS(
        @WebParam(name = "CREATEDEBRANCHREST_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        CREATEDEBRANCHRESTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.CREATEDEBRANCHRESTIOPKRES
     */
    @WebMethod(operationName = "CreateDEBranchRestIO")
    @WebResult(name = "CREATEDEBRANCHREST_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/CreateDEBranchRestIORequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/CreateDEBranchRestIOResponse")
    public CREATEDEBRANCHRESTIOPKRES createDEBranchRestIO(
        @WebParam(name = "CREATEDEBRANCHREST_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        CREATEDEBRANCHRESTIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.CREATEDEDRAFTISSUERMAINTFSFSRES
     */
    @WebMethod(operationName = "CreateDEDraftIssuerMaintFS")
    @WebResult(name = "CREATEDEDRAFTISSUERMAINT_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/CreateDEDraftIssuerMaintFSRequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/CreateDEDraftIssuerMaintFSResponse")
    public CREATEDEDRAFTISSUERMAINTFSFSRES createDEDraftIssuerMaintFS(
        @WebParam(name = "CREATEDEDRAFTISSUERMAINT_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        CREATEDEDRAFTISSUERMAINTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.CREATEDEDRAFTISSUERMAINTIOPKRES
     */
    @WebMethod(operationName = "CreateDEDraftIssuerMaintIO")
    @WebResult(name = "CREATEDEDRAFTISSUERMAINT_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/CreateDEDraftIssuerMaintIORequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/CreateDEDraftIssuerMaintIOResponse")
    public CREATEDEDRAFTISSUERMAINTIOPKRES createDEDraftIssuerMaintIO(
        @WebParam(name = "CREATEDEDRAFTISSUERMAINT_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        CREATEDEDRAFTISSUERMAINTIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.CREATEDEMULTIOFFSETFSFSRES
     */
    @WebMethod(operationName = "CreateDEMultiOffsetFS")
    @WebResult(name = "CREATEDEMULTIOFFSET_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/CreateDEMultiOffsetFSRequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/CreateDEMultiOffsetFSResponse")
    public CREATEDEMULTIOFFSETFSFSRES createDEMultiOffsetFS(
        @WebParam(name = "CREATEDEMULTIOFFSET_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        CREATEDEMULTIOFFSETFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.CREATEDEMULTIOFFSETIOPKRES
     */
    @WebMethod(operationName = "CreateDEMultiOffsetIO")
    @WebResult(name = "CREATEDEMULTIOFFSET_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/CreateDEMultiOffsetIORequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/CreateDEMultiOffsetIOResponse")
    public CREATEDEMULTIOFFSETIOPKRES createDEMultiOffsetIO(
        @WebParam(name = "CREATEDEMULTIOFFSET_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        CREATEDEMULTIOFFSETIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.CREATEMJRNLTEMPLATEFSFSRES
     */
    @WebMethod(operationName = "CreateMjrnlTemplateFS")
    @WebResult(name = "CREATEMJRNLTEMPLATE_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/CreateMjrnlTemplateFSRequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/CreateMjrnlTemplateFSResponse")
    public CREATEMJRNLTEMPLATEFSFSRES createMjrnlTemplateFS(
        @WebParam(name = "CREATEMJRNLTEMPLATE_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        CREATEMJRNLTEMPLATEFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.CREATEMJRNLTEMPLATEIOPKRES
     */
    @WebMethod(operationName = "CreateMjrnlTemplateIO")
    @WebResult(name = "CREATEMJRNLTEMPLATE_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/CreateMjrnlTemplateIORequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/CreateMjrnlTemplateIOResponse")
    public CREATEMJRNLTEMPLATEIOPKRES createMjrnlTemplateIO(
        @WebParam(name = "CREATEMJRNLTEMPLATE_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        CREATEMJRNLTEMPLATEIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.CREATEMJRNLBOOKFSFSRES
     */
    @WebMethod(operationName = "CreateMjrnlbookFS")
    @WebResult(name = "CREATEMJRNLBOOK_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/CreateMjrnlbookFSRequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/CreateMjrnlbookFSResponse")
    public CREATEMJRNLBOOKFSFSRES createMjrnlbookFS(
        @WebParam(name = "CREATEMJRNLBOOK_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        CREATEMJRNLBOOKFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.CREATEMJRNLBOOKIOPKRES
     */
    @WebMethod(operationName = "CreateMjrnlbookIO")
    @WebResult(name = "CREATEMJRNLBOOK_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/CreateMjrnlbookIORequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/CreateMjrnlbookIOResponse")
    public CREATEMJRNLBOOKIOPKRES createMjrnlbookIO(
        @WebParam(name = "CREATEMJRNLBOOK_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        CREATEMJRNLBOOKIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.CREATESINGLEJRNLFSFSRES
     */
    @WebMethod(operationName = "CreateSingleJrnlFS")
    @WebResult(name = "CREATESINGLEJRNL_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/CreateSingleJrnlFSRequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/CreateSingleJrnlFSResponse")
    public CREATESINGLEJRNLFSFSRES createSingleJrnlFS(
        @WebParam(name = "CREATESINGLEJRNL_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        CREATESINGLEJRNLFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.CREATESINGLEJRNLIOPKRES
     */
    @WebMethod(operationName = "CreateSingleJrnlIO")
    @WebResult(name = "CREATESINGLEJRNL_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/CreateSingleJrnlIORequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/CreateSingleJrnlIOResponse")
    public CREATESINGLEJRNLIOPKRES createSingleJrnlIO(
        @WebParam(name = "CREATESINGLEJRNL_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        CREATESINGLEJRNLIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.DELETEDEBATCHBROWSERFSFSRES
     */
    @WebMethod(operationName = "DeleteDEBatchBrowserFS")
    @WebResult(name = "DELETEDEBATCHBROWSER_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/DeleteDEBatchBrowserFSRequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/DeleteDEBatchBrowserFSResponse")
    public DELETEDEBATCHBROWSERFSFSRES deleteDEBatchBrowserFS(
        @WebParam(name = "DELETEDEBATCHBROWSER_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        DELETEDEBATCHBROWSERFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.DELETEDEBATCHBROWSERIOPKRES
     */
    @WebMethod(operationName = "DeleteDEBatchBrowserIO")
    @WebResult(name = "DELETEDEBATCHBROWSER_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/DeleteDEBatchBrowserIORequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/DeleteDEBatchBrowserIOResponse")
    public DELETEDEBATCHBROWSERIOPKRES deleteDEBatchBrowserIO(
        @WebParam(name = "DELETEDEBATCHBROWSER_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        DELETEDEBATCHBROWSERIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.DELETEDEBRANCHRESTFSFSRES
     */
    @WebMethod(operationName = "DeleteDEBranchRestFS")
    @WebResult(name = "DELETEDEBRANCHREST_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/DeleteDEBranchRestFSRequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/DeleteDEBranchRestFSResponse")
    public DELETEDEBRANCHRESTFSFSRES deleteDEBranchRestFS(
        @WebParam(name = "DELETEDEBRANCHREST_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        DELETEDEBRANCHRESTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.DELETEDEBRANCHRESTIOPKRES
     */
    @WebMethod(operationName = "DeleteDEBranchRestIO")
    @WebResult(name = "DELETEDEBRANCHREST_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/DeleteDEBranchRestIORequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/DeleteDEBranchRestIOResponse")
    public DELETEDEBRANCHRESTIOPKRES deleteDEBranchRestIO(
        @WebParam(name = "DELETEDEBRANCHREST_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        DELETEDEBRANCHRESTIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.DELETEDEDRAFTISSUERMAINTFSFSRES
     */
    @WebMethod(operationName = "DeleteDEDraftIssuerMaintFS")
    @WebResult(name = "DELETEDEDRAFTISSUERMAINT_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/DeleteDEDraftIssuerMaintFSRequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/DeleteDEDraftIssuerMaintFSResponse")
    public DELETEDEDRAFTISSUERMAINTFSFSRES deleteDEDraftIssuerMaintFS(
        @WebParam(name = "DELETEDEDRAFTISSUERMAINT_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        DELETEDEDRAFTISSUERMAINTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.DELETEDEDRAFTISSUERMAINTIOPKRES
     */
    @WebMethod(operationName = "DeleteDEDraftIssuerMaintIO")
    @WebResult(name = "DELETEDEDRAFTISSUERMAINT_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/DeleteDEDraftIssuerMaintIORequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/DeleteDEDraftIssuerMaintIOResponse")
    public DELETEDEDRAFTISSUERMAINTIOPKRES deleteDEDraftIssuerMaintIO(
        @WebParam(name = "DELETEDEDRAFTISSUERMAINT_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        DELETEDEDRAFTISSUERMAINTIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.DELETEDEMULTIOFFSETFSFSRES
     */
    @WebMethod(operationName = "DeleteDEMultiOffsetFS")
    @WebResult(name = "DELETEDEMULTIOFFSET_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/DeleteDEMultiOffsetFSRequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/DeleteDEMultiOffsetFSResponse")
    public DELETEDEMULTIOFFSETFSFSRES deleteDEMultiOffsetFS(
        @WebParam(name = "DELETEDEMULTIOFFSET_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        DELETEDEMULTIOFFSETFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.DELETEDEMULTIOFFSETIOPKRES
     */
    @WebMethod(operationName = "DeleteDEMultiOffsetIO")
    @WebResult(name = "DELETEDEMULTIOFFSET_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/DeleteDEMultiOffsetIORequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/DeleteDEMultiOffsetIOResponse")
    public DELETEDEMULTIOFFSETIOPKRES deleteDEMultiOffsetIO(
        @WebParam(name = "DELETEDEMULTIOFFSET_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        DELETEDEMULTIOFFSETIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.DELETEMJRNLTEMPLATEFSFSRES
     */
    @WebMethod(operationName = "DeleteMjrnlTemplateFS")
    @WebResult(name = "DELETEMJRNLTEMPLATE_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/DeleteMjrnlTemplateFSRequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/DeleteMjrnlTemplateFSResponse")
    public DELETEMJRNLTEMPLATEFSFSRES deleteMjrnlTemplateFS(
        @WebParam(name = "DELETEMJRNLTEMPLATE_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        DELETEMJRNLTEMPLATEFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.DELETEMJRNLTEMPLATEIOPKRES
     */
    @WebMethod(operationName = "DeleteMjrnlTemplateIO")
    @WebResult(name = "DELETEMJRNLTEMPLATE_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/DeleteMjrnlTemplateIORequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/DeleteMjrnlTemplateIOResponse")
    public DELETEMJRNLTEMPLATEIOPKRES deleteMjrnlTemplateIO(
        @WebParam(name = "DELETEMJRNLTEMPLATE_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        DELETEMJRNLTEMPLATEIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.DELETEMJRNLBOOKFSFSRES
     */
    @WebMethod(operationName = "DeleteMjrnlbookFS")
    @WebResult(name = "DELETEMJRNLBOOK_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/DeleteMjrnlbookFSRequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/DeleteMjrnlbookFSResponse")
    public DELETEMJRNLBOOKFSFSRES deleteMjrnlbookFS(
        @WebParam(name = "DELETEMJRNLBOOK_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        DELETEMJRNLBOOKFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.DELETEMJRNLBOOKIOPKRES
     */
    @WebMethod(operationName = "DeleteMjrnlbookIO")
    @WebResult(name = "DELETEMJRNLBOOK_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/DeleteMjrnlbookIORequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/DeleteMjrnlbookIOResponse")
    public DELETEMJRNLBOOKIOPKRES deleteMjrnlbookIO(
        @WebParam(name = "DELETEMJRNLBOOK_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        DELETEMJRNLBOOKIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.DELETESINGLEJRNLFSFSRES
     */
    @WebMethod(operationName = "DeleteSingleJrnlFS")
    @WebResult(name = "DELETESINGLEJRNL_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/DeleteSingleJrnlFSRequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/DeleteSingleJrnlFSResponse")
    public DELETESINGLEJRNLFSFSRES deleteSingleJrnlFS(
        @WebParam(name = "DELETESINGLEJRNL_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        DELETESINGLEJRNLFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.DELETESINGLEJRNLIOPKRES
     */
    @WebMethod(operationName = "DeleteSingleJrnlIO")
    @WebResult(name = "DELETESINGLEJRNL_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/DeleteSingleJrnlIORequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/DeleteSingleJrnlIOResponse")
    public DELETESINGLEJRNLIOPKRES deleteSingleJrnlIO(
        @WebParam(name = "DELETESINGLEJRNL_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        DELETESINGLEJRNLIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.MODIFYDEBRANCHRESTFSFSRES
     */
    @WebMethod(operationName = "ModifyDEBranchRestFS")
    @WebResult(name = "MODIFYDEBRANCHREST_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/ModifyDEBranchRestFSRequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/ModifyDEBranchRestFSResponse")
    public MODIFYDEBRANCHRESTFSFSRES modifyDEBranchRestFS(
        @WebParam(name = "MODIFYDEBRANCHREST_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        MODIFYDEBRANCHRESTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.MODIFYDEBRANCHRESTIOPKRES
     */
    @WebMethod(operationName = "ModifyDEBranchRestIO")
    @WebResult(name = "MODIFYDEBRANCHREST_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/ModifyDEBranchRestIORequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/ModifyDEBranchRestIOResponse")
    public MODIFYDEBRANCHRESTIOPKRES modifyDEBranchRestIO(
        @WebParam(name = "MODIFYDEBRANCHREST_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        MODIFYDEBRANCHRESTIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.MODIFYDEDRAFTISSUERMAINTFSFSRES
     */
    @WebMethod(operationName = "ModifyDEDraftIssuerMaintFS")
    @WebResult(name = "MODIFYDEDRAFTISSUERMAINT_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/ModifyDEDraftIssuerMaintFSRequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/ModifyDEDraftIssuerMaintFSResponse")
    public MODIFYDEDRAFTISSUERMAINTFSFSRES modifyDEDraftIssuerMaintFS(
        @WebParam(name = "MODIFYDEDRAFTISSUERMAINT_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        MODIFYDEDRAFTISSUERMAINTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.MODIFYDEDRAFTISSUERMAINTIOPKRES
     */
    @WebMethod(operationName = "ModifyDEDraftIssuerMaintIO")
    @WebResult(name = "MODIFYDEDRAFTISSUERMAINT_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/ModifyDEDraftIssuerMaintIORequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/ModifyDEDraftIssuerMaintIOResponse")
    public MODIFYDEDRAFTISSUERMAINTIOPKRES modifyDEDraftIssuerMaintIO(
        @WebParam(name = "MODIFYDEDRAFTISSUERMAINT_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        MODIFYDEDRAFTISSUERMAINTIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.MODIFYMJRNLTEMPLATEFSFSRES
     */
    @WebMethod(operationName = "ModifyMjrnlTemplateFS")
    @WebResult(name = "MODIFYMJRNLTEMPLATE_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/ModifyMjrnlTemplateFSRequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/ModifyMjrnlTemplateFSResponse")
    public MODIFYMJRNLTEMPLATEFSFSRES modifyMjrnlTemplateFS(
        @WebParam(name = "MODIFYMJRNLTEMPLATE_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        MODIFYMJRNLTEMPLATEFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.MODIFYMJRNLTEMPLATEIOPKRES
     */
    @WebMethod(operationName = "ModifyMjrnlTemplateIO")
    @WebResult(name = "MODIFYMJRNLTEMPLATE_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/ModifyMjrnlTemplateIORequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/ModifyMjrnlTemplateIOResponse")
    public MODIFYMJRNLTEMPLATEIOPKRES modifyMjrnlTemplateIO(
        @WebParam(name = "MODIFYMJRNLTEMPLATE_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        MODIFYMJRNLTEMPLATEIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.MODIFYMJRNLBOOKFSFSRES
     */
    @WebMethod(operationName = "ModifyMjrnlbookFS")
    @WebResult(name = "MODIFYMJRNLBOOK_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/ModifyMjrnlbookFSRequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/ModifyMjrnlbookFSResponse")
    public MODIFYMJRNLBOOKFSFSRES modifyMjrnlbookFS(
        @WebParam(name = "MODIFYMJRNLBOOK_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        MODIFYMJRNLBOOKFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.MODIFYMJRNLBOOKIOPKRES
     */
    @WebMethod(operationName = "ModifyMjrnlbookIO")
    @WebResult(name = "MODIFYMJRNLBOOK_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/ModifyMjrnlbookIORequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/ModifyMjrnlbookIOResponse")
    public MODIFYMJRNLBOOKIOPKRES modifyMjrnlbookIO(
        @WebParam(name = "MODIFYMJRNLBOOK_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        MODIFYMJRNLBOOKIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.QUERYDEBATCHBROWSERIOFSRES
     */
    @WebMethod(operationName = "QueryDEBatchBrowserIO")
    @WebResult(name = "QUERYDEBATCHBROWSER_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/QueryDEBatchBrowserIORequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/QueryDEBatchBrowserIOResponse")
    public QUERYDEBATCHBROWSERIOFSRES queryDEBatchBrowserIO(
        @WebParam(name = "QUERYDEBATCHBROWSER_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        QUERYDEBATCHBROWSERIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.QUERYDEBRANCHRESTIOFSRES
     */
    @WebMethod(operationName = "QueryDEBranchRestIO")
    @WebResult(name = "QUERYDEBRANCHREST_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/QueryDEBranchRestIORequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/QueryDEBranchRestIOResponse")
    public QUERYDEBRANCHRESTIOFSRES queryDEBranchRestIO(
        @WebParam(name = "QUERYDEBRANCHREST_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        QUERYDEBRANCHRESTIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.QUERYDEMULTIOFFSETIOFSRES
     */
    @WebMethod(operationName = "QueryDEMultiOffsetIO")
    @WebResult(name = "QUERYDEMULTIOFFSET_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/QueryDEMultiOffsetIORequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/QueryDEMultiOffsetIOResponse")
    public QUERYDEMULTIOFFSETIOFSRES queryDEMultiOffsetIO(
        @WebParam(name = "QUERYDEMULTIOFFSET_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        QUERYDEMULTIOFFSETIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.QUERYMJRNLTEMPLATEIOFSRES
     */
    @WebMethod(operationName = "QueryMjrnlTemplateIO")
    @WebResult(name = "QUERYMJRNLTEMPLATE_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/QueryMjrnlTemplateIORequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/QueryMjrnlTemplateIOResponse")
    public QUERYMJRNLTEMPLATEIOFSRES queryMjrnlTemplateIO(
        @WebParam(name = "QUERYMJRNLTEMPLATE_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        QUERYMJRNLTEMPLATEIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.QUERYMJRNLBOOKIOFSRES
     */
    @WebMethod(operationName = "QueryMjrnlbookIO")
    @WebResult(name = "QUERYMJRNLBOOK_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/QueryMjrnlbookIORequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/QueryMjrnlbookIOResponse")
    public QUERYMJRNLBOOKIOFSRES queryMjrnlbookIO(
        @WebParam(name = "QUERYMJRNLBOOK_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        QUERYMJRNLBOOKIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.QUERYSINGLEJRNLIOFSRES
     */
    @WebMethod(operationName = "QuerySingleJrnlIO")
    @WebResult(name = "QUERYSINGLEJRNL_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/QuerySingleJrnlIORequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/QuerySingleJrnlIOResponse")
    public QUERYSINGLEJRNLIOFSRES querySingleJrnlIO(
        @WebParam(name = "QUERYSINGLEJRNL_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        QUERYSINGLEJRNLIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.QUERYTELLERIOFSRES
     */
    @WebMethod(operationName = "QueryTellerIO")
    @WebResult(name = "QUERYTELLER_IOFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/QueryTellerIORequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/QueryTellerIOResponse")
    public QUERYTELLERIOFSRES queryTellerIO(
        @WebParam(name = "QUERYTELLER_IOFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        QUERYTELLERIOFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.REOPENDEBRANCHRESTFSFSRES
     */
    @WebMethod(operationName = "ReopenDEBranchRestFS")
    @WebResult(name = "REOPENDEBRANCHREST_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/ReopenDEBranchRestFSRequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/ReopenDEBranchRestFSResponse")
    public REOPENDEBRANCHRESTFSFSRES reopenDEBranchRestFS(
        @WebParam(name = "REOPENDEBRANCHREST_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        REOPENDEBRANCHRESTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.REOPENDEBRANCHRESTIOPKRES
     */
    @WebMethod(operationName = "ReopenDEBranchRestIO")
    @WebResult(name = "REOPENDEBRANCHREST_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/ReopenDEBranchRestIORequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/ReopenDEBranchRestIOResponse")
    public REOPENDEBRANCHRESTIOPKRES reopenDEBranchRestIO(
        @WebParam(name = "REOPENDEBRANCHREST_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        REOPENDEBRANCHRESTIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.REOPENDEDRAFTISSUERMAINTFSFSRES
     */
    @WebMethod(operationName = "ReopenDEDraftIssuerMaintFS")
    @WebResult(name = "REOPENDEDRAFTISSUERMAINT_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/ReopenDEDraftIssuerMaintFSRequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/ReopenDEDraftIssuerMaintFSResponse")
    public REOPENDEDRAFTISSUERMAINTFSFSRES reopenDEDraftIssuerMaintFS(
        @WebParam(name = "REOPENDEDRAFTISSUERMAINT_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        REOPENDEDRAFTISSUERMAINTFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.REOPENDEDRAFTISSUERMAINTIOPKRES
     */
    @WebMethod(operationName = "ReopenDEDraftIssuerMaintIO")
    @WebResult(name = "REOPENDEDRAFTISSUERMAINT_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/ReopenDEDraftIssuerMaintIORequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/ReopenDEDraftIssuerMaintIOResponse")
    public REOPENDEDRAFTISSUERMAINTIOPKRES reopenDEDraftIssuerMaintIO(
        @WebParam(name = "REOPENDEDRAFTISSUERMAINT_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        REOPENDEDRAFTISSUERMAINTIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.REVERSECOMMONREVERSALFSFSRES
     */
    @WebMethod(operationName = "ReverseCommonReversalFS")
    @WebResult(name = "REVERSECOMMONREVERSAL_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/ReverseCommonReversalFSRequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/ReverseCommonReversalFSResponse")
    public REVERSECOMMONREVERSALFSFSRES reverseCommonReversalFS(
        @WebParam(name = "REVERSECOMMONREVERSAL_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        REVERSECOMMONREVERSALFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.REVERSECOMMONREVERSALIOPKRES
     */
    @WebMethod(operationName = "ReverseCommonReversalIO")
    @WebResult(name = "REVERSECOMMONREVERSAL_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/ReverseCommonReversalIORequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/ReverseCommonReversalIOResponse")
    public REVERSECOMMONREVERSALIOPKRES reverseCommonReversalIO(
        @WebParam(name = "REVERSECOMMONREVERSAL_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        REVERSECOMMONREVERSALIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.REVERSETELLERFSFSRES
     */
    @WebMethod(operationName = "ReverseTellerFS")
    @WebResult(name = "REVERSETELLER_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/ReverseTellerFSRequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/ReverseTellerFSResponse")
    public REVERSETELLERFSFSRES reverseTellerFS(
        @WebParam(name = "REVERSETELLER_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        REVERSETELLERFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.REVERSETELLERIOPKRES
     */
    @WebMethod(operationName = "ReverseTellerIO")
    @WebResult(name = "REVERSETELLER_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/ReverseTellerIORequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/ReverseTellerIOResponse")
    public REVERSETELLERIOPKRES reverseTellerIO(
        @WebParam(name = "REVERSETELLER_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        REVERSETELLERIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.SINGLEAUTHORIZEFSFSRES
     */
    @WebMethod(operationName = "SingleAuthorizeFS")
    @WebResult(name = "SINGLEAUTHORIZE_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/SingleAuthorizeFSRequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/SingleAuthorizeFSResponse")
    public SINGLEAUTHORIZEFSFSRES singleAuthorizeFS(
        @WebParam(name = "SINGLEAUTHORIZE_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        SINGLEAUTHORIZEFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.SINGLEAUTHORIZEIOPKRES
     */
    @WebMethod(operationName = "SingleAuthorizeIO")
    @WebResult(name = "SINGLEAUTHORIZE_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/SingleAuthorizeIORequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/SingleAuthorizeIOResponse")
    public SINGLEAUTHORIZEIOPKRES singleAuthorizeIO(
        @WebParam(name = "SINGLEAUTHORIZE_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        SINGLEAUTHORIZEIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.SINGLEDELETEFSFSRES
     */
    @WebMethod(operationName = "SingleDeleteFS")
    @WebResult(name = "SINGLEDELETE_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/SingleDeleteFSRequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/SingleDeleteFSResponse")
    public SINGLEDELETEFSFSRES singleDeleteFS(
        @WebParam(name = "SINGLEDELETE_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        SINGLEDELETEFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.SINGLEDELETEIOPKRES
     */
    @WebMethod(operationName = "SingleDeleteIO")
    @WebResult(name = "SINGLEDELETE_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/SingleDeleteIORequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/SingleDeleteIOResponse")
    public SINGLEDELETEIOPKRES singleDeleteIO(
        @WebParam(name = "SINGLEDELETE_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        SINGLEDELETEIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.SINGLENEWFSFSRES
     */
    @WebMethod(operationName = "SingleNewFS")
    @WebResult(name = "SINGLENEW_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/SingleNewFSRequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/SingleNewFSResponse")
    public SINGLENEWFSFSRES singleNewFS(
        @WebParam(name = "SINGLENEW_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        SINGLENEWFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.SINGLENEWIOPKRES
     */
    @WebMethod(operationName = "SingleNewIO")
    @WebResult(name = "SINGLENEW_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/SingleNewIORequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/SingleNewIOResponse")
    public SINGLENEWIOPKRES singleNewIO(
        @WebParam(name = "SINGLENEW_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        SINGLENEWIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.BATCHTOTDELETEIOPKRES
     */
    @WebMethod(operationName = "BatchTotDeleteIO")
    @WebResult(name = "BATCHTOTDELETE_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/BatchTotDeleteIORequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/BatchTotDeleteIOResponse")
    public BATCHTOTDELETEIOPKRES batchTotDeleteIO(
        @WebParam(name = "BATCHTOTDELETE_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        BATCHTOTDELETEIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.MULTINEWFSFSRES
     */
    @WebMethod(operationName = "MultiNewFS")
    @WebResult(name = "MULTINEW_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/MultiNewFSRequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/MultiNewFSResponse")
    public MULTINEWFSFSRES multiNewFS(
        @WebParam(name = "MULTINEW_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        MULTINEWFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.CREATETELLERFSFSRES
     */
    @WebMethod(operationName = "CreateTellerFS")
    @WebResult(name = "CREATETELLER_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/CreateTellerFSRequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/CreateTellerFSResponse")
    public CREATETELLERFSFSRES createTellerFS(
        @WebParam(name = "CREATETELLER_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        CREATETELLERFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.CREATETELLERIOPKRES
     */
    @WebMethod(operationName = "CreateTellerIO")
    @WebResult(name = "CREATETELLER_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/CreateTellerIORequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/CreateTellerIOResponse")
    public CREATETELLERIOPKRES createTellerIO(
        @WebParam(name = "CREATETELLER_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        CREATETELLERIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.MULTIDELETEFSFSRES
     */
    @WebMethod(operationName = "MultiDeleteFS")
    @WebResult(name = "MULTIDELETE_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/MultiDeleteFSRequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/MultiDeleteFSResponse")
    public MULTIDELETEFSFSRES multiDeleteFS(
        @WebParam(name = "MULTIDELETE_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        MULTIDELETEFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.DELETETELLERIOPKRES
     */
    @WebMethod(operationName = "DeleteTellerIO")
    @WebResult(name = "DELETETELLER_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/DeleteTellerIORequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/DeleteTellerIOResponse")
    public DELETETELLERIOPKRES deleteTellerIO(
        @WebParam(name = "DELETETELLER_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        DELETETELLERIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.BATCHAUTHORIZEIOPKRES
     */
    @WebMethod(operationName = "BatchAuthorizeIO")
    @WebResult(name = "BATCHAUTHORIZE_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/BatchAuthorizeIORequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/BatchAuthorizeIOResponse")
    public BATCHAUTHORIZEIOPKRES batchAuthorizeIO(
        @WebParam(name = "BATCHAUTHORIZE_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        BATCHAUTHORIZEIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.MULTIDELETEIOPKRES
     */
    @WebMethod(operationName = "MultiDeleteIO")
    @WebResult(name = "MULTIDELETE_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/MultiDeleteIORequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/MultiDeleteIOResponse")
    public MULTIDELETEIOPKRES multiDeleteIO(
        @WebParam(name = "MULTIDELETE_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        MULTIDELETEIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.MULTIAUTHORIZEIOPKRES
     */
    @WebMethod(operationName = "MultiAuthorizeIO")
    @WebResult(name = "MULTIAUTHORIZE_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/MultiAuthorizeIORequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/MultiAuthorizeIOResponse")
    public MULTIAUTHORIZEIOPKRES multiAuthorizeIO(
        @WebParam(name = "MULTIAUTHORIZE_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        MULTIAUTHORIZEIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.MULTIAUTHORIZEFSFSRES
     */
    @WebMethod(operationName = "MultiAuthorizeFS")
    @WebResult(name = "MULTIAUTHORIZE_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/MultiAuthorizeFSRequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/MultiAuthorizeFSResponse")
    public MULTIAUTHORIZEFSFSRES multiAuthorizeFS(
        @WebParam(name = "MULTIAUTHORIZE_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        MULTIAUTHORIZEFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.DELETETELLERFSFSRES
     */
    @WebMethod(operationName = "DeleteTellerFS")
    @WebResult(name = "DELETETELLER_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/DeleteTellerFSRequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/DeleteTellerFSResponse")
    public DELETETELLERFSFSRES deleteTellerFS(
        @WebParam(name = "DELETETELLER_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        DELETETELLERFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.MULTINEWIOPKRES
     */
    @WebMethod(operationName = "MultiNewIO")
    @WebResult(name = "MULTINEW_IOPK_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/MultiNewIORequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/MultiNewIOResponse")
    public MULTINEWIOPKRES multiNewIO(
        @WebParam(name = "MULTINEW_IOPK_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        MULTINEWIOPKREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.BATCHTOTDELETEFSFSRES
     */
    @WebMethod(operationName = "BatchTotDeleteFS")
    @WebResult(name = "BATCHTOTDELETE_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/BatchTotDeleteFSRequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/BatchTotDeleteFSResponse")
    public BATCHTOTDELETEFSFSRES batchTotDeleteFS(
        @WebParam(name = "BATCHTOTDELETE_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        BATCHTOTDELETEFSFSREQ requestMsg);

    /**
     * 
     * @param requestMsg
     * @return
     *     returns com.bayeesoft.stub.BATCHAUTHORIZEFSFSRES
     */
    @WebMethod(operationName = "BatchAuthorizeFS")
    @WebResult(name = "BATCHAUTHORIZE_FSFS_RES", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "ResponseMsg")
    @Action(input = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/BatchAuthorizeFSRequest", output = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com/FCUBSDEServiceSEI/BatchAuthorizeFSResponse")
    public BATCHAUTHORIZEFSFSRES batchAuthorizeFS(
        @WebParam(name = "BATCHAUTHORIZE_FSFS_REQ", targetNamespace = "http://fcubs.ofss.com/service/FCUBSDEService", partName = "RequestMsg")
        BATCHAUTHORIZEFSFSREQ requestMsg);

}
