
package com.bayeesoft.stub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "FCUBSDEService", targetNamespace = "http://FCUBSDEService.types.ws.gw.fcubs.ofss.com", wsdlLocation = "http://10.1.12.71:8101/FCUBSDEService/FCUBSDEService?WSDL")
public class FCUBSDEService
    extends Service
{

    private final static URL FCUBSDESERVICE_WSDL_LOCATION;
    private final static WebServiceException FCUBSDESERVICE_EXCEPTION;
    private final static QName FCUBSDESERVICE_QNAME = new QName("http://FCUBSDEService.types.ws.gw.fcubs.ofss.com", "FCUBSDEService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.1.12.71:8101/FCUBSDEService/FCUBSDEService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FCUBSDESERVICE_WSDL_LOCATION = url;
        FCUBSDESERVICE_EXCEPTION = e;
    }

    public FCUBSDEService() {
        super(__getWsdlLocation(), FCUBSDESERVICE_QNAME);
    }

    public FCUBSDEService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FCUBSDESERVICE_QNAME, features);
    }

    public FCUBSDEService(URL wsdlLocation) {
        super(wsdlLocation, FCUBSDESERVICE_QNAME);
    }

    public FCUBSDEService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FCUBSDESERVICE_QNAME, features);
    }

    public FCUBSDEService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FCUBSDEService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FCUBSDEServiceSEI
     */
    @WebEndpoint(name = "FCUBSDEServiceSEI")
    public FCUBSDEServiceSEI getFCUBSDEServiceSEI() {
        return super.getPort(new QName("http://FCUBSDEService.types.ws.gw.fcubs.ofss.com", "FCUBSDEServiceSEI"), FCUBSDEServiceSEI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FCUBSDEServiceSEI
     */
    @WebEndpoint(name = "FCUBSDEServiceSEI")
    public FCUBSDEServiceSEI getFCUBSDEServiceSEI(WebServiceFeature... features) {
        return super.getPort(new QName("http://FCUBSDEService.types.ws.gw.fcubs.ofss.com", "FCUBSDEServiceSEI"), FCUBSDEServiceSEI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FCUBSDESERVICE_EXCEPTION!= null) {
            throw FCUBSDESERVICE_EXCEPTION;
        }
        return FCUBSDESERVICE_WSDL_LOCATION;
    }

}
